server:
  port: 8080
  url: 127.0.0.1:${server.port}

spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
      config:
        group: DEFAULT_GROUP
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
  config:
    import:
      - nacos:tcss-${spring.profiles.active}.yaml
  profiles:
    active: @profiles.active@
  datasource:
    username: ${tcss.db.username}
    password: ${tcss.db.password}
    url: jdbc:mysql://${tcss.db.host}:${tcss.db.port}/${tcss.db.name}?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

logging:
  level:
    com.alibaba.nacos: error
    root: info
  file:
    path: ./log

# 暴露监控
management:
  endpoints:
    web:
      exposure:
        include: '*'
