server:
  port: 8080

spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
      config:
        group: DEFAULT_GROUP
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
  config:
    import:
      - nacos:tcss-${spring.profiles.active}.yaml
  profiles:
    active: @profiles.active@


logging:
  level:
    com.alibaba.nacos: error
    root: error
  file:
    path: ./log

# 暴露监控
management:
  endpoints:
    web:
      exposure:
        include: '*'
